<?
$aMenuLinks = Array(
    Array(
        "Девелопмент", 
        "/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "проектирование", 
        "/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "строительство", 
        "/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "эксплуатация", 
        "/", 
        Array(), 
        Array(), 
        "" 
    ),
);
?>