<?
$aMenuLinks = Array(
    Array(
        "О компании", 
        "/about/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Проекты", 
        "/projects/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Контакты", 
        "/contacts/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Вакансии", 
        "/jobs/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Новости", 
        "/news/", 
        Array(), 
        Array(), 
        "" 
    ),
);
?>